name: Publish Python Package

# on:
#   push:
#     branches:
#       - main

on:
  workflow_run:
    workflows: ["Black Formatter"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Use runner Python in Poetry (sanity)
        run: poetry env use python

      - name: Install dependencies
        run: poetry install

      - name: Update last digit of semantic version
        run: |
          version=$(poetry version | awk '{print $2}')
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF++; print}')
          poetry version $new_version

      - name: Commit and push new version to main
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Bump version to $new_version" -a
          git push origin main --force

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package to PyPI
        run: |
          poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
